name: Log.gd Unit Tests
run-name: ${{ github.head_ref || github.ref_name }}-log-ci

on:
  # pull_request:
  workflow_dispatch:
  push:


concurrency:
  group: log-ci${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "GDUnit Tests"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ['4.1', '4.1.3', '4.2', '4.2.2']
        godot-status: ['stable']
        include:
          - godot-version: '4.3'
            godot-status: 'beta1'

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
      # run unit tests
      - uses: MikeSchulze/gdUnit4-action@v1.0.5
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: ${{ matrix.godot-status }}
          version: 'installed'
          paths: |
            res://test/
          timeout: 5
          upload-report: false
